  version: '2'
  services:
  nodejs:
    image: 3iamlucifer12/node-js
    ports:
      - 8080:80
    volumes:
    - .:/usr/src/app

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: rohan
      MYSQL_PASSWORD: rohan
      MYSQL_RANDOM_ROOT_PASSWORD: rohan
    volumes:
      - db:/var/lib/mysql

volumes:
  nodejs:
  db:
